# Generated by Django 3.0.5 on 2020-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='background',
            name='has_FHD',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='has_HD',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='has_LQ',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='image_FHD',
            field=models.ImageField(blank=True, null=True, upload_to='main/background', verbose_name='Изображение FHD'),
        ),
        migrations.AlterField(
            model_name='background',
            name='image_HD',
            field=models.ImageField(blank=True, null=True, upload_to='main/background', verbose_name='Изображение HD'),
        ),
        migrations.AlterField(
            model_name='background',
            name='image_LQ',
            field=models.ImageField(blank=True, null=True, upload_to='main/background', verbose_name='Изображение LQ'),
        ),
    ]
