# Generated by Django 3.0.5 on 2020-05-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200523_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name': 'Фон', 'verbose_name_plural': 'Фоны'},
        ),
    ]
