# Generated by Django 3.0.5 on 2020-05-29 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_bang_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='lvl',
            field=models.IntegerField(default=None, verbose_name='Уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Опыт'),
            preserve_default=False,
        ),
    ]
