# Generated by Django 3.0.5 on 2020-05-31 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200529_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='character_id',
            field=models.IntegerField(default=0, verbose_name='Id персонажа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
