# Generated by Django 3.0.5 on 2020-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200531_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lvl',
            field=models.IntegerField(default='1', verbose_name='Уровень'),
        ),
    ]
